services:
    app:
        build: .
        ports:
            - 8001:8001
        volumes:
            - .:/app/
        env_file:
            - ./.env
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
        depends_on: []
        restart: always
        networks:
            - backend_videos

volumes:
    postgres_data:

networks:
    backend_videos:
